### PR TITLE
Jim's work on array interpretations

### PR DESCRIPTION
**Pull request by jpivarski**
I'll be working in this (probably long-lived) pull request.

If you get rid of `HelloWorld` and `HelloWorldTest` in your branch, there would be no merge conflicts. I'm only going to be working in this "interpretation" directory and suite of tests.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
I'd probably say that we could just commit to master while we're both working on completely different parts of the tree w/no interactions between.

**Comment by jpivarski** [comment]
I know, it probably looks like overkill, but I'll be working with limited resources and I wanted to make sure that you didn't pull in any large jars that would break my Chromebook. So I'll keep working in the branch.

**Comment by jpivarski** [comment]
Speaking of dependencies, I was thinking of adding one. What do you think if the final output of the interpretation is an Arrow buffer? I don't know what the output is supposed to be, but it's probably very close to Arrow, and that might have multiple uses. The alternative is me making up interface classes that behave the same way.

**Comment by PerilousApricot** [comment]
I'm fine adding deps (if it's arrow, it'll transitively end up in the deps
via Spark anyway). I'll have to dig into the DSv2 api to see exactly how
the columns are stored, but I'm sure it'll be remarkably similar in any case

>

**Comment by jpivarski** [comment]
@PerilousApricot:

I'm going to merge this in now because it's working. It only does one branch type: non-jagged doubles, but let's make sure that we can integrate this before loading in all the types. (Adding them will be easy, but changing the interface after adding them would be difficult.)

It deliberately follows uproot closely—I could perhaps add uproot line numbers in the comments so that we can cross-reference for future updating and debugging...

So, next milestone: read a flat branch of doubles from a ROOT file into an `Array`?

**Pull request merged**
