### PR TITLE
fixes #26: {int1, int2, int4, int8, float4, float8} × {scalar, array, slice} now work

### LINKED ISSUE #26: Fixed-length arrays are improperly parsed
The following testcase fails:

https://github.com/PerilousApricot/spark-ttree/blob/a3c8e2a1d63d9069ab86a4d5125eaaa8a6b44647/src/test/java/edu/vanderbilt/accre/spark_ttree/TTreeDataSourceIntegrationTest.java#L55-L56

The first line (correctly) deserializes the 8-bit int variant, while the 2nd returns all zeros, though it is the correct shape. Tracing through, the correct bytestream is in the buffers (`ArrayI8: 0000000101010202028080808181818282827F7F7F7E7E7E7D7D7D` in hex), but something isn't lining up with the array interpretation

The tree is generated with https://github.com/PerilousApricot/spark-ttree/blob/bugfix/for-jim2/testdata/gen/make.py

### PR DESCRIPTION
**Pull request by jpivarski**
I'm going to make sure that the less-symmetric data in "all-types.root" can be read properly. Although I'm testing it in pure Java, it should fix the problems you've been seeing in Spark with fixed-width and variable-width arrays.

### CODE REVIEW

**Comment by jpivarski** [comment]
@PerilousApricot The generated file is a little weird (probable mistake with signed/unsigned), but the scalars at least agree with uproot:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running edu.vanderbilt.accre.root_proxy.TTreeTest
[TRACE] 11:39:58.561 e.v.a.l.s.S.SlimTBasket - getbasket len: 36
[0, 1, 2, -2147483648, -2147483647, -2147483646, 2147483647, 2147483646, 2147483645]
```

```python
>>> import uproot
>>> uproot.open("testdata/all-types.root")["Events"].array("ScalarI32")
array([          0,           1,           2, -2147483648, -2147483647,
       -2147483646,  2147483647,  2147483646,  2147483645], dtype=int32)
```

**Comment by PerilousApricot** [comment]
@jpivarski -- I "think" that should be right if you're doing the unsigned. I generate them in `testdata/gen/make.py` -- but the idea is to do `[0,1,2,MIN_INT, MIN_INT -1, MIN_INT - 2, MAX_INT, MAX_INT - 1, MAX_INT - 2]` ... the idea being that I wanna make sure I'm properly hitting the ends of the ranges

**Comment by jpivarski** [comment]
Merge this whenever you feel comfortable doing so: I'm done working on it. It ensures that all the `{int1, int2, int4, int8, float4, float8} × {scalar, array, slice}` cases work. The new tests are at the end of `TTreeDataSourceUnitTest.java`, but I verified that these tests call the functions with the same arguments as Spark (by running `TTreeDataSourceIntegrationTest.java`.

Oh, and you don't really have any examples of array data with different values in each element of the array—that symmetry has yet to be broken. However, I did find a bug related to that and I'm 95% sure that I fixed it properly.

Types that haven't really been covered: booleans, strings, unsigned types, ROOT's Float16 and Double32.

**Comment by PerilousApricot** [comment]
Thanks for all the help! I'll look at the patch -- I'll work on the more complicated types as I come across them -- trying to figure out the best way to handle the unsigned integers currently, then I'll move on to the other types.

And I like doing as much as possible in the pure Java testing since the integration testing is so slow. It'd be nice to have some sort of "inverse mock" functionality to trace and replay the calls that spark makes downwards

**Comment by PerilousApricot** [comment]
merged, thanks!

**Pull request merged**
